// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prestamos.Loans.Persistence;

#nullable disable

namespace Prestamos.Loans.Persistence.Migrations
{
    [DbContext(typeof(LoansDbContext))]
    [Migration("20220705083350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Loans")
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Prestamos.Loans.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CorrelationId");

                    b.ToTable("Loans", "Loans");
                });

            modelBuilder.Entity("Prestamos.Loans.Domain.Entities.LoanLine", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoanCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("CorrelationId");

                    b.HasIndex("LoanCorrelationId");

                    b.ToTable("LoanLines", "Loans");
                });

            modelBuilder.Entity("Prestamos.Loans.Domain.Entities.LoanLine", b =>
                {
                    b.HasOne("Prestamos.Loans.Domain.Entities.Loan", null)
                        .WithMany("LoanLines")
                        .HasForeignKey("LoanCorrelationId");
                });

            modelBuilder.Entity("Prestamos.Loans.Domain.Entities.Loan", b =>
                {
                    b.Navigation("LoanLines");
                });
#pragma warning restore 612, 618
        }
    }
}
